server:
  port: 8088

spring:
  shardingsphere:
        datasource:
            names: ds0
            ds0:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.jdbc.Driver
                username: edurw
                password: edurw
                url: jdbc:mysql://172.16.86.47:3306/edu_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
                filters: stat,wall,log4j
                maxActive: 20
                initialSize: 1
                maxWait: 60000
                minIdle: 1
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: select 'x'
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxOpenPreparedStatements: 20
                connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
        sharding:
            tables:
                user_course_order:
                    actual-data-nodes: ds$->{0}.user_course_order_$->{0..9}
                    table-strategy:
                        inline:
                            sharding-column: user_id
                            algorithm-expression: user_course_order_$->{user_id % 10}
                    key-generator:
                        column: id
                        type: SNOWFLAKE
                        props:
                            worker.id: 1


        props:
            sql:
                show: true
            check:
                table:
                    metadata:
                        # 是否在启动时检查分表元数据一致性
                        enabled: false
  rabbitmq:
    host: 172.16.86.47
    port: 5672
    username: root
    password: 123456
  klock:
    address: 172.16.179.134:6379
  redis:
    host: 172.16.179.134
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password:

rocketmq:
  name-server: 172.16.179.134:9876
  producer:
    group: edu_group
  consumer:
    group: edu_group

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    #启用shutdown端点，以便支持优雅停机
    shutdown:
      enabled: true

#分布式链路追踪--调整SpringBoot日志输出级别
logging:
  config: classpath:logback.xml

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.lagou.edu
  local:
    # 短時本地緩存，主要用于要求时效较高的配置
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
      expireAfterAccessInMillis: 40000