#eureka server服务端口
server:
  port: 8761
spring:
  application:
    name: edu-eureka-boot # 应用名称，应用名称会在Eureka中作为服务名称
eureka:
  instance:
    hostname: localhost  # 当前eureka实例的主机名
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    #eureka server刷新readCacheMap的时间 默认30s
    response-cache-update-interval-ms: 3000
    #启用主动失效，并且每次主动失效检测间隔为3s 默认60s
    eviction-interval-timer-in-ms: 3000
    use-read-only-response-cache: false
  dashboard:
    enabled: true