server:
  port: 8090

spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        git:
          uri: https://github.com/github-fxf/lagou-edu-repo.git
          username: 245958539@qq.com
          password: fxf19940827zxc
          default-label: main