server:
  port: 8090

spring:
  data:
    mongodb:
      database: edu_comment
      host: 172.16.179.134
      port: 27017
  klock:
    address: 172.16.179.134:6379
  rabbitmq:
    host: 172.16.86.47
    port: 5672
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    #启用shutdown端点，以便支持优雅停机
    shutdown:
      enabled: true

#分布式链路追踪--调整SpringBoot日志输出级别
logging:
  config: classpath:logback.xml