server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/css,application/json
    min-response-size: 512
    tomcat:
      # 1. Maximum number of connections that the server will accept and process at any time given time
      # max-connections最好不配置，根据默认的连接器协议HTTP/1.1，tomcat自动探测环境的不同，为本item赋值：BIO时是max-threads，NIO/NIO时是10000，APR/native是8192
      # 本质上它指的是tomcat可以建立多少个socket连接，注意即时socket已经建立但是如果max-threads是无空闲的，那么任务应该在线程池的队列里
      # max-connections: 100
      # 2. Maximum amount of worker threads
      max-threads: 200
      # 3. Minimum amount of worker threads
      min-spare-threads: 100
      # 4. TCP accept 队列的长度：理论上只要还有worker thread可用它就会是接近为空队列，所以这个配置是说当到达max-threads时还能接受多少请求
      accept-count: 200
      # This specifies the character encoding used to decode the URI bytes, after %xx decoding the URL.
      uri-encoding: UTF-8
    error:
      includeStacktrace: ALWAYS
spring:
  oauth:
    client_id: test_client
    client_secret: test_secret
    scope: read
    grant_type: password
    refresh_grant_type: refresh_token
  rabbitmq:
    host: 113.31.119.154
    port: 5672
    username: root
    password: 123456
  klock:
    address: 113.31.105.128:6379
  redis:
    host: 113.31.105.128
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password:

zookeeper:
  address: 113.31.105.128:2181
cloud:
  sentinel:
    transport:
      dashboard: localhost:30918
    eager: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    #启用shutdown端点，以便支持优雅停机
    shutdown:
      enabled: true

#分布式链路追踪--调整SpringBoot日志输出级别
logging:
  config: classpath:logback.xml

ribbon:
  ConnectTimeout: 3000 # timeout of connect to server
  ReadTimeout: 3000 # timeout of read
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000 # 设置thread 和semaphore 两种隔离策略的超时时间，默认1000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 500

feign:
  # Feign 客户端配置，对应 FeignClientProperties 配置属性类
  client:
    # config 配置项是 Map 类型。key 为 Feign 客户端的名字，value 为 FeignClientConfiguration 对象
    config:
      # 全局级别配置
      default:
        logger-level: FULL
  #        logger-level: BASIC
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
remote:
  feign:
    edu-course-boot:
      name: edu-course-boot
edu:
  swagger:
    # 是否启用
    enable: true
    base:
      # 扫描的包，多个包使用逗号隔开
      package: com.lagou.edu
    contact:
      email: leo@lagou.com
      name: leo
      url: http://edufront.lagou.com
    description:
    title: ${spring.application.name} API Documents
    url: http://edufront.lagou.com
    version: 0.0.1
    groupName: edu-front-boot
    # 自定义参数配置，可配置N个
    parameter-config:
      - name: Authorization
        description: 公共参数, access_token
        # header, cookie, body, query
        type: header
        data-type: String
        required: false
        # 测试接口时，自动填充token的值
        default-value: "access_token"

# knife4j配置
knife4j:
  enable: ${edu.swagger.enable}
  basic:
    enable: false
    username: admin
    password: admin

wx:
  mp:
    config:
      appId:   # （一个公众号的appid）
      secret:  #（公众号的appsecret）
      token: edufront   # （接口配置里的Token值）
      aesKey: EobkgHl1ChHrjnSIjUntW0fuj3k57NQFtDlhV2dg22Q  # （接口配置里的EncodingAESKey值）