server:
  port: 8095

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://113.31.119.154:3306/edu_message?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: edurw
    password: edurw
  klock:
    address: 113.31.105.128:6379
  rabbitmq:
    host: 113.31.119.154
    port: 5672
    username: root
    password: 123456
  redis:
    host: 113.31.105.128
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password:
  security:
    oauth2:
      jwt:
        signingKey: 123456
  thymeleaf:
    #清除缓存
    cache: false
    mode: LEGACYHTML5 #非严格模式
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
rocketmq:
  name-server: 113.31.105.128:9876
  producer:
    group: edu_group
  consumer:
    group: edu_group

webSocket:
  origin: http://localhost
  context: /push
  port: 8899

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    #启用shutdown端点，以便支持优雅停机
    shutdown:
      enabled: true

#分布式链路追踪--调整SpringBoot日志输出级别
logging:
  config: classpath:logback.xml